### ISSUE TITLE
Merge with https://github.com/IvanMalison/org-projectile?

### ISSUE THREAD

**Issue by IvanMalison** [waymondo/org-repo-todo#4]
I was thinking about the adding the ability to org-projectile to specify per repository TODO files, and I noticed that your repository already offers this functionality. Would you ever consider trying to merge this with https://github.com/IvanMalison/org-projectile

**Comment by waymondo** [comment]
I'm open to sharing whatever code is relevant from `org-repo-todo` for `org-projectile`, but on first glance I see them as packages with slightly different philosophies. The two differences I'm seeing are:

* `org-repo-todo` is primarily for capturing todos and visiting a single file within the root directory. `org-projectile` works out of a master file for all projects.
* `org-projectile` relies on `projectile` (which I use personally, but I don't see the need to require for my little package).

Is there a feature/approach you had in mind that `org-repo-todo` has that you'd like to include in your package?

**Comment by IvanMalison** [comment]
I was mainly just thinking that I wanted to add the option to do per project TODO management in org-projectile.

But you may be right that the dependency on projectile is a pretty important philosophical difference. I would say that I care less about avoiding dependencies than I care about reinventing the wheel as far as repository discovery is concerned, but I understand that your priorities may be different.

**Comment by IvanMalison** [comment]
I added this feature to org-projectile so I'm going to close this.

**Comment by waymondo** [comment]
rock on :metal:
